### ISSUE TITLE
Making a great impact

### ISSUE THREAD

**Issue by vitkarpov** [oleggromov/module#1]
Hey, dude!

The Modules gonna be the greatest dependencies management system ever! I really encourage you to get ~~the shit~~ this done and make a great impact to javascript community.

Yours, a javascript hacker.

**Comment by oleggromov** [comment]
I don't think `module` can make any great impact, because in fact it's just a clone of existing `define`. Nevertheless, it is finally built based on the specially written (and very simple of course) [PubSub module](https://github.com/oleggromov/pubsub) which can enlighten and inspire anybody as it has done to me. 
I've also found an erroneous array manipulating pattern which will be written about soon. 

Thanks for a backing word, bro! :+1:
